### ISSUE TITLE
Indicate the estimated difficulty of an issue by using a variable amount of 🌶️.

### ISSUE THREAD

**Issue by L-Bolt** [IntelligentRoboticsLab/dnt-hulk#113]
As issues increase, the benefit of quickly indicating the estimated difficulty of an issue becomes ever more clear.
If an issue has a clear indication of its estimated difficulty, people can more easily assess the time requirements needed to fix the issue.
Furthermore, newer members could focus on the less spicy issues, whereas more experienced members can feast on the most spiciest of issues. 

This issue would have a spice-rating of 🌶️, whereas implementing a walking engine would have a spice-rating of 🌶️🌶️🌶️🌶️🌶️

**Comment by Redjeepkaiser** [comment]
@oxkitsune do we want this for yggdrasil as well?

**Comment by oxkitsune** [comment]
I added the labels as default labels for new repositories! This means they will need to be added manually to existing repositories. I’ve added them to `nidhogg`, and will do the same for `yggdrasil` in a few minutes.
