### ISSUE TITLE
Things to do/look into after `GORE`

### ISSUE THREAD

**Issue by Aemulation** [IntelligentRoboticsLab/dnt-hulk#32]
- [ ] Localization is messed up.
- [ ] Behaviour (especially the goali). Robots walk into the goal because they think it's the other side of the field.
- [ ] We need a bigger network switch because we're actually not allowed to setup a wireless network.
- [x] We need to label the NAO chargers with the name of the robot on a sticker close to the plug.
- [x] SPL protocol has changed, look into that.
- [x] Look into public transport before we get to Bordaux.
- [ ] We should let a full team of NAO's play more often because only then can we truly check behaviour.
- [ ] We should practice getting ready for a match. Who takes which robot/charger to the field, who takes a laptop, screwdrivers etc.
- [ ] Implement golden test before match.
- [ ] Get a better whistle (knijpfluit)
- [ ] Somehow set the NAO's in a ready state for the second half, instead of waiting on the gamecontroller.
- [ ] More sponsors, maybe sponsor tiers like Hulks?
- [ ] More referee practice.

**Comment by Redjeepkaiser** [comment]
@dweprinz can this be closed?

**Comment by dweprinz** [comment]
some todos still relevant
